SNOW-878366 Don't require user or password for particular authenticators
snowflakedb/snowflake-connector-net pull request #726
Opened 2023-07-28 12:27 UTC by sfc-gh-pfus

2023-07-28 13:15 UTC, sfc-gh-pbulawa approved these changes

2023-07-31 05:38 UTC, sfc-gh-dprzybysz approved these changes

2023-07-31 09:40 UTC, sfc-gh-knozderko requested changes

2023-07-31 09:40 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSessionProperty.cs
> +                List<string> authenticatorsWithoutPassword = new List<string>()
you could use var here

2023-07-31 09:40 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSessionProperty.cs
> +                List<string> authenticatorsWithoutUsername = new List<string>()
use var

2023-07-31 09:40 UTC, sfc-gh-knozderko commented on Snowflake.Data.Tests/SFSessionPropertyTest.cs
> +                testCaseThatDefaultForUseProxyIsFalse,
is the comma at the end really needed?

2023-07-31 09:40 UTC, sfc-gh-knozderko commented on README.md
> +  Optionally, `USER` can set set. In that case only if user authenticated via external browser matches the one from configuration, authentication will complete.
set set?

2023-07-31 12:07 UTC, sfc-gh-knozderko approved these changes

2023-07-31 12:18 UTC, merged