SNOW-893835 Arrow - support for multi-chunk results
snowflakedb/snowflake-connector-net pull request #771
Opened 2023-09-04 18:47 UTC by sfc-gh-dstempniak

### Description
Please explain the changes you made here.

### Checklist
- [ ] Code compiles correctly
- [ ] Code is formatted according to [Coding Conventions](../CodingConventions.md)
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`dotnet test`)
- [ ] Extended the README / documentation, if necessary
- [ ] Provide JIRA issue id (if possible) or GitHub issue id in PR name

2023-09-06 07:15 UTC, sfc-gh-pfus commented on Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
> +                BaseResultChunk resultChunk;
Can we use ternary operator to init here?

2023-09-06 12:22 UTC, sfc-gh-mhofman requested changes

2023-09-06 12:22 UTC, sfc-gh-mhofman commented on Snowflake.Data.Tests/UnitTests/ArrowResultChunkTest.cs
> +            for (var i = 0; i < RowCountBatchOne; ++i)
simply: while (_chunk.Next()); ?

2023-09-06 12:22 UTC, sfc-gh-mhofman commented on Snowflake.Data.Tests/UnitTests/ArrowResultSetTest.cs
>              Assert.IsFalse(_arrowResultSet.Rewind());
cannot place comment below - should we do sth about ln 152 or can we get rid of the comment?

2023-09-06 12:32 UTC, sfc-gh-pmotacki commented on Snowflake.Data.Tests/UnitTests/ArrowResultChunkTest.cs
> +            _chunk.Next();
If I understand correctly this return false. It is needed to rewind to the end of previous chunk?

2023-09-11 07:49 UTC, sfc-gh-mhofman approved these changes

2023-09-11 17:08 UTC, sfc-gh-dstempniak commented on Snowflake.Data.Tests/IntegrationTests/SFDbCommandIT.cs
> +                        Assert.AreEqual(counter.ToString(), reader.GetString(0));
uniform returns random numbers, so by definition it should not be tested, but ok, I added comment

2023-09-11 17:09 UTC, sfc-gh-dstempniak commented on Snowflake.Data/Core/BaseResultChunk.cs
> +        public int ColCount { get; protected set; }
I changed to ColumncCount, I agree it is better

2023-09-11 21:43 UTC, sfc-gh-igarish commented
I saw many "public" method changes. Are we going to mark it as a BCR? Also do we added result format changes from ARROW to JSON and vice versa like "alter session set DOTNET_RESULT_FORMAT = 'ARROW' | 'JSON'"? Default should be arrow like JDBC/ODBC/GO drivers.

2023-09-12 15:20 UTC, sfc-gh-dstempniak commented
@sfc-gh-igarish thank you for your comment. I recreated IResultChunk interface not to do BCR. Now interface of all public methods in public classes remain the same.
DOTNET_QUERY_RESULT_FORMAT parameter will be added to GS in SNOW-893840. Arrow code is already unit-tested, integration tests will be added later.

2023-09-13 07:53 UTC, merged