fix dns names with underscore
snowflakedb/snowflake-connector-net pull request #834
Opened 2023-12-14 17:42 UTC by sfc-gh-bculberson

### Description
DNS names with underscores are not valid in the .net framework. This will construct a working HOST name by replacing with - which is how Snowflake solves for this use case, but users had to manually set HOST.

### Checklist
- [ ] Code compiles correctly
- [ ] Code is formatted according to [Coding Conventions](../CodingConventions.md)
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`dotnet test`)
- [ ] Extended the README / documentation, if necessary
- [ ] Provide JIRA issue id (if possible) or GitHub issue id in PR name

2024-01-09 13:46 UTC, gboucher90 commented
Hey,

We just encountered this issue in Production. Indeed it seems OpenSSL which is used by the .Net Core runtime implementation doesn't handle well underscores:
https://github.com/dotnet/runtime/issues/58722
https://mta.openssl.org/pipermail/openssl-dev/2015-August/002411.html

Would it be possible to have this code released?

Thank you!

2024-01-09 14:46 UTC, sfc-gh-knozderko commented
We are planning to release it in the nearest release.

2024-01-10 09:11 UTC, sfc-gh-pbulawa requested changes

2024-01-10 09:11 UTC, sfc-gh-pbulawa commented on Snowflake.Data/Core/Session/SFSessionProperty.cs
> +                string compliantAccountName = properties[SFSessionProperty.ACCOUNT].Replace('_','-');
We require a possibility to disable the replacement by the parameter in a connection string similar to JDBC to mitigate the risk of privatelink connections not working: [Reasoning for JDBC](https://community.snowflake.com/s/article/Behaviour-Change-Release-information-associated-with-Snowflake-JDBC-driver-version-3-13-25)

2024-01-15 08:35 UTC, sfc-gh-pbulawa commented
PR #848 implements the feature. Thanks for the contribution.

2024-01-15 08:35 UTC, closed without merging