Fix lowercase db or schema in connection string
snowflakedb/snowflake-connector-net pull request #844
Opened 2024-01-09 18:42 UTC by Sielnix

### Description
There's a bug, that having specified database or schema name in connection string, that contains any lowercase letter, throws exception during connection opening.

This PR fixes that.

### Checklist
- [x] Code compiles correctly
- [x] Code is formatted according to [Coding Conventions](../CodingConventions.md)
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`dotnet test`)
- [ ] Extended the README / documentation, if necessary
- [ ] Provide JIRA issue id (if possible) or GitHub issue id in PR name

2024-01-09 18:42 UTC, Sielnix commented
I have read the CLA Document and I hereby sign the CLA

2024-03-01 16:44 UTC, sfc-gh-mhofman requested changes

2024-03-01 16:44 UTC, sfc-gh-mhofman commented on Snowflake.Data/Core/Session/SFSession.cs
> +            return name == string.Empty ? name : $"\"{name.Replace("\"", "\"\"")}\"";
Please make sure the name isn't already wrapped with quotes.
Make sure if connection tests are passing after this fix.

2024-03-01 16:44 UTC, sfc-gh-mhofman commented on Snowflake.Data/Core/Session/SFSession.cs
> +            queryParams[RestParams.SF_QUERY_DB] = EscapeDbObjectForUrl(properties.TryGetValue(SFSessionProperty.DB, out dbValue) ? dbValue : "");
Can you provide some unit tests for this change?

2026-04-30 15:57 UTC, sfc-gh-mcepiga commented
closing after years of inactivity

2026-04-30 15:57 UTC, closed without merging