SNOW-1168205 iceberg table compliance testing
snowflakedb/snowflake-connector-net pull request #908
Opened 2024-04-04 20:49 UTC by sfc-gh-mhofman

### Description
Please explain the changes you made here.

### Checklist
- [ ] Code compiles correctly
- [ ] Code is formatted according to [Coding Conventions](../blob/master/CodingConventions.md)
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`dotnet test`)
- [ ] Extended the README / documentation, if necessary
- [ ] Provide JIRA issue id (if possible) or GitHub issue id in PR name

2024-04-10 13:27 UTC, sfc-gh-knozderko requested changes

2024-04-10 13:27 UTC, sfc-gh-knozderko commented on Snowflake.Data.Tests/IcebergTests/TestIcebergTable.cs
> +                var expected = new Object[] {I32, I64, Dec, Dbl, Flt, Txt, B1, B0, _dt, _tm, _ntz, _ltz, _bi};
why Object uppercase?

2024-04-10 13:27 UTC, sfc-gh-knozderko commented on Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
> +    <LangVersion>9</LangVersion>
what was it needed to?

2024-04-12 12:20 UTC, sfc-gh-mhofman commented on Snowflake.Data.Tests/IcebergTests/TestIcebergTable.cs
> +            object[] NullifyWithinRow(object[] expected, int index)
Fixed parameter name and moved to util class

2024-04-12 12:27 UTC, sfc-gh-mhofman commented on Snowflake.Data.Tests/IcebergTests/TestIcebergTable.cs
> +            string ByteArrayToString(byte[] ba)
done

2024-04-15 11:46 UTC, sfc-gh-knozderko approved these changes

2024-04-15 12:14 UTC, merged