Update README.md (small typos)
snowflakedb/snowflake-connector-net pull request #910
Opened 2024-04-05 18:54 UTC by mweeden2

I fixed two typos in the README.

2024-04-05 18:55 UTC, mweeden2 commented
I have read the CLA Document and I hereby sign the CLA

2024-04-08 13:05 UTC, sfc-gh-mhofman requested changes

2024-04-08 13:05 UTC, sfc-gh-mhofman commented on README.md
> +    - `{pathToThePrivateKeyFile}` is the path to the file containing the encrypted private key.
There is below an example showing it is not encrypted.

2025-10-06 09:00 UTC, sfc-gh-mhofman commented on README.md
> +    - `{pathToThePrivateKeyFile}` is the path to the file containing the encrypted private key.
@mweeden2 
I think the same was spot here:
https://github.com/snowflakedb/snowflake-connector-net/pull/1053/files
Is this clear in this way?

2026-04-23 16:55 UTC, sfc-gh-mcepiga commented
closing after a year of inactivity

2026-04-23 16:55 UTC, closed without merging