Pool/SNOW-937188 changed session behavior
snowflakedb/snowflake-connector-net pull request #937
Opened 2024-04-29 19:05 UTC by sfc-gh-mhofman

### Description
- API to switch settings for the new pool
- API to get pool from the manger based on connection string (and if appropriate password)

### Checklist
- [ ] Code compiles correctly
- [ ] Code is formatted according to [Coding Conventions](../blob/master/CodingConventions.md)
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`dotnet test`)
- [ ] Extended the README / documentation, if necessary
- [ ] Provide JIRA issue id (if possible) or GitHub issue id in PR name

2024-05-02 12:20 UTC, sfc-gh-knozderko requested changes

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SessionPool.cs
> +        public int GetMinPoolSize() => _poolConfig.MinPoolSize;
for old pool we don't use minPoolSize. It is returned default value but actually it doesn't matter.
I'm thinking if throwing an exception for parameters not used by given version of pool could be maybe less confusing. But maybe not... I'm just thinking.

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSession.cs
> +            if (!String.IsNullOrEmpty(finalSessionValue))
string lowercase

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSession.cs
> +                if (!String.IsNullOrEmpty(initialSessionValue) && initialSessionValue != finalSessionValue)
string lowercase, you should respect quoted values strictly but ignore case for unquoted values.

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
> +                    i => (ChangedSessionBehavior)Enum.Parse(typeof(ChangedSessionBehavior), i),
would it work with lower case/upper case as well?

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
> +                    s => !string.IsNullOrEmpty(s) && Enum.IsDefined(typeof(ChangedSessionBehavior), s),
would it work with lower case/upper case as well?

2024-05-02 12:20 UTC, sfc-gh-knozderko commented on Snowflake.Data.Tests/IntegrationTests/ConnectionChangedSessionIT.cs
> +    public class ConnectionChangedSessionIT : SFBaseTest
I would rename it to express the fact that it is a test for the new pool

2024-05-06 08:06 UTC, sfc-gh-mhofman commented on Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
> +        public static SnowflakeDbSessionPool GetPool(string connectionString, SecureString password)
but it's an API for a user of the driver

2024-05-07 11:16 UTC, sfc-gh-knozderko commented on Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
> +        public static SnowflakeDbSessionPool GetPool(string connectionString, SecureString password)
but it would be nice to have at least one test using this method

2024-05-07 12:51 UTC, sfc-gh-knozderko requested changes

2024-05-07 12:51 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SessionPool.cs
> +            return IsMultiplePoolsVersion()
If we decide to throw an error for GetMinPoolSize, then maybe we should do the same for others method which have no meaning for the old pool like GetWaitForIdleSessionTimeout(), etc.

2024-05-07 12:51 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SFSession.cs
> +                wasUnquoted1 || wasUnquoted2 ? StringComparison.InvariantCulture : StringComparison.InvariantCultureIgnoreCase);
let's use Oridinal versions instead cultural invariant ones

2024-05-07 14:48 UTC, sfc-gh-knozderko commented on Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
> +        public static SnowflakeDbSessionPool GetPool(string connectionString, SecureString password)
I added one usage in tests

2024-05-07 15:07 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SessionPool.cs
> +        public void SetMaxPoolSize(int newMaxPoolSize)
done

2024-05-08 08:14 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Session/SessionPool.cs
> +            return IsMultiplePoolsVersion()
fixed

2024-05-10 11:09 UTC, sfc-gh-knozderko commented on Snowflake.Data/Core/Authenticator/IAuthenticator.cs
>                      !session.properties.TryGetValue(SFSessionProperty.PRIVATE_KEY, out var pkContent))
just wndering if here we should do something similar `|| string.IsNullOrEmpty(pkContent)`

2024-05-10 12:06 UTC, sfc-gh-knozderko approved these changes

2024-05-13 12:29 UTC, sfc-gh-mhofman commented on Snowflake.Data/Core/Session/SFSessionProperty.cs
> +                if (IsRequired(sessionProperty, properties) && string.IsNullOrEmpty(properties[sessionProperty]))
IsRequired method is modifying required flag of the parameter USER according to authenticator so it won't throw

2024-05-13 13:20 UTC, merged